### ISSUE TITLE
No longer supports node 8.2.0

### ISSUE THREAD

**Issue by XuluWarrior** [percy/percy-script#12]
https://github.com/percy/percy-agent/pull/467 removed support for node 8

Installation on node 8 breaks when running puppeteer/puppeteer install.js

**Comment by wwilsman** [comment]
Hi @XuluWarrior, thanks for pointing this out!

I've created a PR and will release a new version with an updated Node engine value in the package.json, so installation in Node 8 should no longer work (since it is end-of-life as of the beginning of the year).

**Comment by wwilsman** [comment]
#13 Released as v1.1
