### ISSUE TITLE
axios security vulnerability

### ISSUE THREAD

**Issue by rmccar** [percy/percy-script#20]
axios which is a dependancy of percy-agent has a security vulnerability.
To fix this, axios needs to be updated to v0.21.1. This has been done in percy-agent v0.28.6.

percy-script should be updated to use percy-agent v0.28.6 and fix this vulnerability.

https://snyk.io/test/npm/axios/0.19.0

**Comment by Robdel12** [comment]
Hey @rmccar thanks for opening the issue! `@percy/script` has a pretty loose dep on `@percy/agent`: https://github.com/percy/percy-script/blob/master/package.json#L16 

You should be able to force the transitive dependency update by reinstalling `@percy/script`: `npm i -D @percy/script` (or `yarn add -D @percy/script`)
